# code: language=ansible
---
- name: Converge
  hosts: all

  pre_tasks:
    # Workaround for Fedora 41 https://github.com/ansible/ansible/issues/84206
    - name: Install python3-libdnf5
      become: true
      ansible.builtin.command: dnf install -y python3-libdnf5
      when: ansible_facts.pkg_mgr == 'dnf5'
      changed_when: false

    - name: Install jdk 8
      become: true
      ansible.builtin.package:
        name: java-1.8.0-openjdk-headless
        state: present

    - name: Install find
      become: true
      ansible.builtin.package:
        name: findutils
        state: present

  roles:
    - role: ansible-role-maven
      maven_version: '3.9.4'
      maven_install_dir: /opt/maven

  post_tasks:
    - name: Verify default maven facts
      ansible.builtin.assert:
        that:
          - ansible_local.maven.general.version is defined
          - ansible_local.maven.general.home is defined
