---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-maven-fedora
    image: fedora:34

provisioner:
  name: ansible

verifier:
  name: testinfra
  directory: ../single/tests
