# code: language=ansible
---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

    - name: Install jdk 8
      become: true
      ansible.builtin.apt:
        name: openjdk-8-jdk-headless
        state: present

  roles:
    - role: ansible-role-maven
      maven_version: '3.9.1'
      maven_install_dir: /opt/maven

  post_tasks:
    - name: Verify default maven facts
      ansible.builtin.assert:
        that:
          - ansible_local.maven.general.version is defined
          - ansible_local.maven.general.home is defined
