---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-maven-ubuntu-min
    image: ubuntu:16.04
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: ubuntu-min

verifier:
  name: testinfra
  directory: ../single/tests
  lint:
    name: flake8
