---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

platforms:
  - name: ansible-role-maven-debian-max
    image: debian:12

provisioner:
  name: ansible

verifier:
  name: testinfra
  directory: ../single/tests
