---
- name: Converge
  hosts: all

  pre_tasks:
    # Travis CI doesn't provide all the Debian dependencies for the full JDK.
    - name: install jre-headless 8
      become: yes
      apt:
        name: openjdk-8-jre-headless
        state: present

  roles:
    - role: ansible-role-maven
      maven_version: '3.6.3'
      maven_install_dir: /opt/maven

  post_tasks:
    - name: verify default maven facts
      assert:
        that:
          - ansible_local.maven.general.version is defined
          - ansible_local.maven.general.home is defined
