# code: language=ansible
---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Install jdk 8
      become: true
      ansible.builtin.package:
        name: java-1.8.0-openjdk-headless
        state: present

  roles:
    - role: ansible-role-maven
      maven_version: '3.9.1'
      maven_install_dir: /opt/maven

  post_tasks:
    - name: Verify default maven facts
      ansible.builtin.assert:
        that:
          - ansible_local.maven.general.version is defined
          - ansible_local.maven.general.home is defined
