---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

platforms:
  - name: ansible-role-maven-ubuntu-max
    image: ubuntu:22.04

provisioner:
  name: ansible

verifier:
  name: testinfra
