---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-maven-debian-wheezy
    image: debian:7
  - name: ansible-role-maven-debian-jessie
    image: debian:8
  - name: ansible-role-maven-ubuntu-trusty
    image: ubuntu:14.04
  - name: ansible-role-maven-ubuntu-xenial
    image: ubuntu:16.04
  - name: ansible-role-maven-centos-6
    image: centos:6
  - name: ansible-role-maven-centos-7
    image: centos:7
  - name: ansible-role-maven-fedora-25
    image: fedora:25
  - name: ansible-role-maven-opensuse-leap
    image: opensuse:42.2

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
