---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-maven-centos-max
    image: centos:7
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible

verifier:
  name: testinfra
  directory: ../single/tests
