---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-maven-centos-7
    image: centos:7

provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    destroy: ../default/destroy.yml
    prepare: ../default/prepare.yml
  lint:
    name: ansible-lint

scenario:
  name: centos-max

verifier:
  name: testinfra
  directory: ../single/tests/
  lint:
    name: flake8
