---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-maven-debian-wheezy
    image: debian:7

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: debian-min

verifier:
  name: testinfra
  directory: ../single/tests
  lint:
    name: flake8
